Ready for Code Review
camfilho/responsive-design pull request #1
Opened 2019-10-03 15:36 UTC by camfilho

Opening a pull request to check for linters errors.

2019-10-04 12:35 UTC, maelfosso requested changes
Hello coders,

Thank you for that first version :+1: 
However there is a lot that should be done. The main thing to say is that what you did doesn't look like the original one.

- [x] CSS styles should use media queries for 3 breakpoints
- small: max-width around 700
- medium: max-width around 1000
- large: mwidth over 1000
 You should rework by taking that in consideration because it's not what you did.

- [ ] Remove the empty **heading**, I mean empty **h1 to h6**

- [x] Please, put space between the elements in the footer
![Screenshot from 2019-10-04 13-07-40](https://user-images.githubusercontent.com/8848104/66206415-f83a2d80-e6a7-11e9-9089-56adfe87f85f.png)

- [ ] The main navigation bar and the second doesn't look identical. Also the logo must appear when we scroll down. Also, correct the appearance at different breakpoints. Also the navigation bar is **fixed**

- [x] **Top 3 articles section** 
![Screenshot from 2019-10-04 13-21-51](https://user-images.githubusercontent.com/8848104/66207155-f1acb580-e6a9-11e9-95bf-23c18414e772.png)
The original don't have space between and around. Also for small screens, the 3 images take the maximum width and are are aligned in one column.

- [ ] The same errors occurs with most of the section from **Latest news section**

Please kindly make the changes.

2019-10-04 12:35 UTC, maelfosso commented on style.css
> +}
That css file doesn't take in consideration all the home page breakpoints..
Please, be sure to identically represent the original page.

2019-10-07 18:48 UTC, whiz25 requested changes
## Good job :+1: 
You have made most of the requested changes but forgot one crucial requirement. Please look at my suggestion below;
- [ ] add the TNW logo. This is a must-have requirement.

### Please make that change and send for another review.

2019-10-07 19:25 UTC, camfilho commented
@whiz25 could you give us a hint of how to achieve it without using Javascript?

thanks in advance

2019-10-07 20:55 UTC, camfilho commented
Added the logo on desktop size.
It appears when we scroll down, as in the original one.

2019-10-07 21:13 UTC, wathigo approved these changes
## Hi @camfilho  and @cerfectus :wave:  
The project looks great and meets all the requirements!

**You may move on** 

_Happy coding :computer:_

2019-10-07 21:15 UTC, merged